# Workflow to Test for Valid Schema and Compatibility
name: Test for Valid Schema and Compatibility

# Trigger the workflow when a pull request is opened or synchronized, and if it's on the 'master' branch
on:
  pull_request:
    branches: [ main ]

# Confluent Cloud Schema Registry Information
env:
  SCHEMA_REGISTRY_URL: ${{ secrets.SCHEMA_REGISTRY_URL }}
  SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: "${{ secrets.SCHEMA_REGISTRY_USERNAME }}:${{ secrets.SCHEMA_REGISTRY_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 20
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      # Step 3: Validate Schema
      - name: Validate Schema
        run: mvn io.confluent:kafka-schema-registry-maven-plugin:validate

      # Step 4: Test Local Schema Compatibility
      - name: Test Local Schema Compatibility
        run: mvn io.confluent:kafka-schema-registry-maven-plugin:test-local-compatibility

      # Step 5: Set Compatibility (May fail for the first run)
      - name: Set Compatibility
        run: mvn io.confluent:kafka-schema-registry-maven-plugin:set-compatibility "-DschemaRegistryUrl=$SCHEMA_REGISTRY_URL" "-DschemaRegistryBasicAuthUserInfo=$SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO"

      # Step 6: Test Schema Compatibility
      - name: Test Schema Compatibility
        run: mvn io.confluent:kafka-schema-registry-maven-plugin:test-compatibility "-DschemaRegistryUrl=$SCHEMA_REGISTRY_URL" "-DschemaRegistryBasicAuthUserInfo=$SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO"
